<#
.SYNOPSIS
    Generates build_info.py at the repo root with build-time constants baked in.

.PARAMETER BuildType
    "consumer" or "owner"

.PARAMETER Version
    Semantic version string, e.g. "1.0.2"

.EXAMPLE
    .\generate_build_info.ps1 -BuildType owner -Version 1.0.2
#>
param(
    [Parameter(Mandatory)][ValidateSet('consumer','owner')][string]$BuildType,
    [string]$Version = "1.0.0"
)

$OwnerMode  = if ($BuildType -eq 'owner') { 'True'  } else { 'False' }
$TrialDays  = if ($BuildType -eq 'owner') { '0'     } else { '7'     }
$IncludeEarn = if ($BuildType -eq 'owner') { 'True' } else { 'False' }

$Timestamp = (Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')

$Content = @"
# AUTO-GENERATED by scripts/generate_build_info.ps1 — DO NOT EDIT
BUILD_TYPE    = '$BuildType'
BUILD_VERSION = '$Version'
BUILD_DATE    = '$Timestamp'
OWNER_MODE    = $OwnerMode
TRIAL_DAYS    = $TrialDays
INCLUDE_EARN  = $IncludeEarn
"@

$Content | Set-Content -Path "$PSScriptRoot\..\build_info.py" -Encoding UTF8
Write-Host "[generate_build_info] Written build_info.py  BUILD_TYPE=$BuildType  VERSION=$Version"
