"""Enhanced Guardian v3 report sections."""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from workers.guardian.guardian_crypto_intel import get_roadmap
from workers.guardian.guardian_threat_intel import ThreatIntelResult


def append_v3_sections(
    base_report: str,
    *,
    target: str,
    subdomains: List[str],
    live_hosts: List[str],
    endpoints: List[str],
    tech_data: List[Dict],
    threat_intel: Optional[ThreatIntelResult] = None,
    recon_notes: str = "",
) -> str:
    techs = sorted(set(t for h in tech_data for t in (h.get("tech") or [])))
    attack_surface = [
        "",
        "---",
        "",
        "## Attack Surface",
        "",
        f"- Primary target: `{target}`",
        f"- Discovered subdomains: **{len(subdomains)}**",
        f"- Live HTTP hosts: **{len(live_hosts)}**",
        f"- Crawled endpoints: **{len(endpoints)}**",
    ]
    if live_hosts[:8]:
        attack_surface.append("- Live URLs:")
        for u in live_hosts[:8]:
            attack_surface.append(f"  - `{u}`")

    recon = [
        "",
        "## Recon Results",
        "",
        recon_notes or f"Subdomain enumeration and HTTP probing completed for `{target}`.",
    ]
    if subdomains[:12]:
        recon.append("")
        recon.append("Sample subdomains:")
        for s in subdomains[:12]:
            recon.append(f"- `{s}`")

    tech_section = [
        "",
        "## Technologies",
        "",
    ]
    if techs:
        tech_section.append(", ".join(f"`{t}`" for t in techs[:40]))
    else:
        tech_section.append("_No technology fingerprint from httpx._")

    extra = attack_surface + recon + tech_section

    if threat_intel:
        extra += ["", threat_intel.to_markdown()]

    extra += ["", get_roadmap().to_markdown()]

    try:
        from workers.guardian.guardian_offensive_lab import load_lab_config
        cfg = load_lab_config()
        if cfg.get("enabled"):
            extra += [
                "",
                "## Offensive Lab",
                "",
                "Network penetration, credential audit, and backdoor detection run in **ATTACK** mode "
                "when the closed lab is acknowledged. See `GUARDIAN_OFFENSIVE_LAB.md`.",
            ]
    except Exception:
        pass

    # Insert before final tool status if present
    marker = "---\n*Report generated by Guardian"
    if marker in base_report:
        return base_report.replace(marker, "\n".join(extra) + "\n\n" + marker)
    return base_report + "\n".join(extra)
